<?php
// $Id$

require_once drupal_get_path('module', 'shrew') .'/lib/InnopacWeb.php';
require_once('File/MARCXML.php');

/**
 * @file
 *
 * @see http://code.google.com/p/shrew/
 */

/**
 * Implementation of hook_help().
 */
function shrew_help($path, $arg) {
  switch ($path) {
    case 'admin/help#shrew':
      return '<p>'. t('Integrates the Shrew library for interacting with Innovative Interfaces integrated library systems and online catalogs.') .'</p>';
    case 'admin/settings/shrew':
      return '<p>'. t('Specify the URI for a III Webpac instance.') .'</p>';
  }
}

/**
 * Implementation of hook_menu().
 */
function shrew_menu() {
  $items['admin/settings/shrew'] = array(
    'title' => 'Shrew settings',
    'description' => 'Control how Shrew works.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shrew_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}


function shrew_admin_settings() {
  $form['shrew_webpac_location'] = array(
    '#type' => 'textfield',
    '#title' => t('Shrew III Webpac location'),
    '#description' => t('Please provide the location of your Webpac instance.'),
    '#default_value' => variable_get('shrew_webpac_location', ''),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}


function shrew_get_library() {
  return drupal_get_path('module', 'shrew') .'/lib/InnopacWeb.php';
}

/**
 * Setter method for webpac location
 *
 * @param $location
 *  URI for Webpac instance
 */
function shrew_set_webpac_location($location) {
  variable_set('shrew_webpac_location', $location);
}


/**
 * Getter method for webpac location
 */
function shrew_get_webpac_location() {
  return variable_get('shrew_webpac_location', NULL);
}

function shrew_require($once = TRUE) {

  $library = shrew_get_library();

  if ($once) {
    require_once './'. $library;
    require_once 'File/MARCXML.php';
  }
  else {
    require './'. $library;
    require 'File/MARCXML.php';
  }
}


/**
 * Helper function to instantiate a new shrewClient
 *
 * @param $webpac_location
 *   URI for III Webpac instance
 * @return
 *   Instance of shrew.
 */
function shrew_init($webpac_location = FALSE) {
  static $shrew = NULL;
  shrew_require();

  if ($webpac_location == FALSE) {
    $webpac_location = shrew_get_webpac_location();
  } 
  
  $shrew = new shrewClient($webpac_location);
  return $shrew;
}


/**
 * Parses a single MARCXML record stored as a string into a File_MARC_Record
 * object
 *
 * @param string $record
 *   string Single MARCXML record
 *
 * @return
 *   File_MARC_Record
 */
function shrew_record_parse($record) {
  $obj = new File_MARCXML($record, 2);
  $mxrecord = $obj->next();
  return $mxrecord;
}


class shrewClient extends InnopacWeb {
  
  /**
 	 * Given a list of record identifiers, returns a list of record objects that
 	 * contain bibliographic information, as well as associated holdings and
 	 * item information.
 	 *
   * @param $id
   *   string of record IDs, separated by spaces
   * @return
   *   array
   */
  public function get_records($id) {
    $out = array();
    $response = parent::getRecords($id);
    if (count($response) > 0) {
      foreach ($response as $r) {
        $srec = new shrewRecord();
        $xml = $r->bibliographicRecord->saveXML();
        $srec->bibliographicRecord = shrew_record_parse($xml);
        $srec->items = $r->items;
        $out[] = $srec;
      }
    }
    return $out;
  }
}
 
/**
 * Subclassing InnopacWeb_Record since we are using shrew_get() to return
 * a slightly different object; shrewRecord->bibliographicRecord is a
 * File_MARC_Record, not a DOMDocument
 */
class shrewRecord extends InnopacWeb_Record {
// public $bibliographicRecord; // File_MARC_Record
// public $items = array(); // array
}
